services:
  - type: web
    name: xeeroo
    env: python
    plan: starter
    buildCommand: "./build.sh"
    startCommand: "gunicorn xeeroo.wsgi:application"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.8"
      - key: DJANGO_DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: "xeeroo.onrender.com,xeeroo.com,www.xeeroo.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://xeeroo.onrender.com,https://xeeroo.com,https://www.xeeroo.com"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_MEDIA_ROOT
        value: "/var/data/media"
    disks:
      - name: xeeroo-media
        mountPath: /var/data
        sizeGB: 1
